
### Criar ocorrência
POST http://localhost:5000/api/ocorrencias
Content-Type: application/json

{
  "tipo": "Incêndio Florestal",
  "gravidade": 5,
  "regiao": "Norte"
}

### Buscar todas
GET http://localhost:5000/api/ocorrencias

### Atualizar ocorrência
PUT http://localhost:5000/api/ocorrencias/1
Content-Type: application/json

{
  "id": 1,
  "tipo": "Incêndio Florestal",
  "gravidade": 4,
  "regiao": "Nordeste"
}

### Deletar ocorrência
DELETE http://localhost:5000/api/ocorrencias/1
